[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = ['ruby']

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'sh install.sh'
# hook_source = '''
# " Required for operations modifying multiple buffers like rename.
# set hidden
#
# let g:LanguageClient_serverCommands = {
#       \ 'vue': ['vls'],
#       \ 'html': [],
#       \ 'css': [],
#       \ 'javascript': ['javascript-typescript-stdio'],
#       \ 'typescript': ['javascript-typescript-stdio'],
#       \ 'ruby': ['language_server-ruby'],
#       \ }
#
# nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
# nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
# nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
# " not stop completion $ & /
# setlocal iskeyword+=$
# setlocal iskeyword+=-
# '''

[[plugins]]
# neosnippet
repo = 'Shougo/neosnippet.vim'
hook_source = '''
"Ctrl+Kにターゲットジャンプ割当
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim']

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['css', 'html', 'less', 'sass', 'scss', 'stylus']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'
hook_source = '''
let g:html5_event_handler_attributes_complete=0
let g:html5_rdfa_attributes_complete=0
let g:html5_microdata_attributes_complete=0
let g:html5_aria_attributes_complete=0
'''

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['css']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c']
hook_source = '''
autocmd FileType c ClangFormatAutoEnable
let g:clang_format#style_options={
  \ "Language": "Cpp",
  \ "BasedOnStyle": "LLVM",
  \ "ContinuationIndentWidth": 2,
  \ "ConstructorInitializerIndentWidth": 2,
  \ }
  '''

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_source = '''
let g:vim_json_syntax_conceal=0
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'
